### PR TITLE
I435

### PR DESCRIPTION
**Pull request by coubeatczech**
pr attempting to solve issue #435

### CODE REVIEW

**Comment by bergmark** [comment]
Thanks!

Are you able to write a test case for this so it doesn't break in the future?

**Comment by coubeatczech** [comment]
Ok, I'll do it.

**Comment by coubeatczech** [comment]
Done.

I'll reorder the commits - put the test first to show that it fails without the `Ptr's`.

**Comment by coubeatczech** [comment]
continuing at #437

**Pull request closed without merging**
