### PR TITLE
Fix dependent compilation when it's triggered by stack

### LINKED ISSUE #457: Dependent compilation failed when building with stack
## Problem statement

- `stack` used in project.
- Project triggered `Fay` programmatically.
- I want to add new `fay` package in dependency list.
- During compilation `stack` used its own `ghc` and `ghc-pkg`.
- `stack` rewrites `HASKELL_SANDBOX_CONFIG`, `GHC_PACKAGE_PATH` environment variables.
- `fay` cannot find new package.

## Impact analysis

- Since project compilation constantly failed I am loosing ability to ship new versions into production.
- This is not a blocker since I can reimplement package functionality in my project.

## Solution Proposal

- Proposed simple analysis for `ghc` and `ghc-pkg` from `ghc-paths`:
- If their paths contained ".stack" inside then:
  - `stack exec -- ghc # for ghc`
  - `stack exec -- ghc-pkg # for ghc-pkg`
- otherwise fallback to previous execution flow.

### PR DESCRIPTION
**Pull request by swamp-agr**
Closes #457 as described in *Solution Proposal* section.

### CODE REVIEW

**Comment by swamp-agr** [comment]
Hi @bergmark, 

Is there any chance to review and accept this PR? I am currently working on isomorphic web framework that uses `fay-websockets` under the hood. I want to ensure that it will be compatible with all build tools. I already tried `cabal` and there were no issues. However, `stack` produced some and I tried to fix them all. 

Best Regards,
@swamp-agr

**Comment by swamp-agr** [comment]
Any chances to merge it in 2018?

**Comment by swamp-agr** [comment]
Happy New Year! 

@bergmark, May I ask you to consider me as co-maintainer for this package?

**Comment by bergmark** [comment]
Sorry I'm so slow, you are more than welcome as a co-maintainer! Thanks

**Comment by bergmark** [comment]
I've sent an invite to the github org, do you have a hackage account?

**Comment by swamp-agr** [comment]
Yes, it's **swamp_agr** (with underscore). BTW, I accepted your invitation. Thank you!

**Comment by bergmark** [comment]
I added you as a hackage maintainer for fay and fay-base as well

**Comment by swamp-agr** [comment]
@bergmark thank you! 
I will do my best!

**Pull request merged**
